function(ConfigurePETSC TARGET)

# Find petsc headers:
FIND_PATH(PETSC_INCLUDE_PATH
    NAMES petsc.h
    PATHS
    "${PETSC_PATH}/include"
    NO_DEFAULT_PATH REQUIRED
    )

if(PETSC_INCLUDE_PATH)
    message(STATUS "Petsc header petsc.h found at " ${PETSC_INCLUDE_PATH})
else()
    message(STATUS "PETSC HEADER PETSC.H NOT FOUND")
endif()

FIND_PATH(PETSCCONF_INCLUDE_PATH
    NAMES petscconf.h
    PATHS
    "${PETSC_PATH}/lib/${CMAKE_BUILD_TYPE}/include"
    NO_DEFAULT_PATH REQUIRED
    )
#get_filename_component(PETSCCONF_INCLUDE_PATH "${PETSCCONF_INCLUDE_PATH}" DIRECTORY )

if(PETSCCONF_INCLUDE_PATH)
    message(STATUS "Petsc header petscconf.h found at " ${PETSCCONF_INCLUDE_PATH})
else()
    message(STATUS "PETSC HEADER PETSCCONF.H NOT FOUND")
endif()

# Find petsc library:
FIND_FILE(PETSC_LIBRARIES
    NAMES libpetsc.lib
    PATHS
    "${PETSC_PATH}/lib/${CMAKE_BUILD_TYPE}"
    NO_DEFAULT_PATH REQUIRED
    )

if(PETSC_LIBRARIES)
    message(STATUS "PETSC library found at " ${PETSC_LIBRARIES})
else()
    message(STATUS "PETSC LIBRARY NOT FOUND")
endif()


if(PETSC_INCLUDE_PATH AND PETSCCONF_INCLUDE_PATH AND PETSC_LIBRARIES)
    SET(PETSC_FOUND YES PARENT_SCOPE)

    TARGET_INCLUDE_DIRECTORIES(${TARGET} PUBLIC ${PETSC_INCLUDE_PATH} ${PETSCCONF_INCLUDE_PATH})
    TARGET_LINK_LIBRARIES(${TARGET} PUBLIC ${PETSC_LIBRARIES})
endif()


endfunction(ConfigurePETSC)

